//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTrongGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.DanhMucAnhs = new HashSet<DanhMucAnh>();
        }
    
        public string SanPhamID { get; set; }
        public string TenSp { get; set; }
        public int LoaiSpID { get; set; }
        public string AnhDaiDien { get; set; }
        public double Gia { get; set; }
        public string TrangThai { get; set; }
        public string Model { get; set; }
        public string MieuTaNgan { get; set; }
        public string MieuTaChiTiet { get; set; }
        public bool TrangThaiXoa { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual ICollection<DanhMucAnh> DanhMucAnhs { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
