//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTrongGo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiKhoan
    {
        public TaiKhoan()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }

        public int TaiKhoanID { get; set; }
        public int LoaiTaiKhoanID { get; set; }
        [Display(Name = "Tên của bạn")]
        [Required(ErrorMessage = "Tên không được trống")]
        public string TenNguoiDung { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Email không được trống")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Email không đúng")]
        public string Email { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        [Display(Name = "Số điện thoại của bạn")]
        [Required(ErrorMessage = "Số điện thoại không được trống")]
        public string Phone { get; set; }
        [Display(Name = "Địa chỉ của bạn")]
        [Required(ErrorMessage = "Địa chỉ không được trống")]
        public string DiaChi { get; set; }
        public bool TrangThaiXoa { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }

        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual LoaiTaiKhoan LoaiTaiKhoan { get; set; }
    }
}
