//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ShopTrongGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public TaiKhoan()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int TaiKhoanID { get; set; }
        public int LoaiTaiKhoanID { get; set; }
        public string TenNguoiDung { get; set; }
        public string Email { get; set; }
        [Required(ErrorMessage = "Please Provide Username", AllowEmptyStrings = false)]
        public string TenDangNhap { get; set; }
        [Required(ErrorMessage = "Please provide password", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string MatKhau { get; set; }
        public string Phone { get; set; }
        public string DiaChi { get; set; }
        public bool TrangThaiXoa { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
    
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual LoaiTaiKhoan LoaiTaiKhoan { get; set; }
    }
}
