//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTrongGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int Id { get; set; }
        public int LoaiDMTin { get; set; }
        public string TenTin { get; set; }
        public string MieuTaNgan { get; set; }
        public string MieuTaChiTiet { get; set; }
        public bool TrangThai { get; set; }
        public Nullable<System.DateTime> NgayXoaTin { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public string NguoiDang { get; set; }
        public string AnhDaiDien { get; set; }
        public string TenKhongDau { get; set; }
    
        public virtual DanhMucTin DanhMucTin { get; set; }
    }
}
