//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoManagerPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoiTac
    {
        public int DoiTacID { get; set; }
        public string TenDoiTac { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public string NoiDung { get; set; }
        public string MieuTaNgan { get; set; }
        public string NguoiDang { get; set; }
        public bool TrangThaiXoa { get; set; }
        public System.DateTime NgayXoa { get; set; }
    }
}
