//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoManagerPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public HoaDon()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }
    
        public int HoaDonID { get; set; }
        public System.DateTime NgayMua { get; set; }
        public int TaiKhoanID { get; set; }
        public bool TrangThaiXoa { get; set; }
        public System.DateTime NgayXoa { get; set; }
    
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
