//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoManagerPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        public int NhaCungCapID { get; set; }
        public string TenNcc { get; set; }
        public string Phone { get; set; }
        public string DiaChi { get; set; }
        public bool TrangThaiXoa { get; set; }
        public System.DateTime NgayXoa { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
    }
}
